version: '3'

services:
  database:
    build:
      context: docker/database
    environment:
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./docker/database/data:/var/lib/mysql
  #     - ./docker/database/backups:/backups
  php-fpm:
    build:
      context: docker/php-fpm
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ./candidate-search-app:/var/www/candidate-search-app
  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./candidate-search-app:/var/www/candidate-search-app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "8081:8081"
      - "443:443"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.0.1
    environment:
      - discovery.type=single-node
      - node.name=elasticlog.elastic
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - http.port=9200
    ports:
      - "9270:9200"
      - "9300:9300"
    volumes:
      - ./docker/elastic/data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.0.1
    environment:
      ELASTICSEARCH_HOSTS: "http://candidate-search-elastic-1:9200"
    ports:
      - 5670:5601
    depends_on:
      - elastic
